### ISSUE TITLE
Making location of Tika tmp configurable.

### ISSUE THREAD

**Issue by dmnyu** [google/go-tika#13]
Making a minor change to the codebase to allow the passing of a path as part of the java.io.tmpdir system property when starting a Tika instance from the go-tika library.

**Comment by tbpg** [comment]
Sounds good to me! Would you like to send a PR? I'm not sure what the API should be, but we can probably sort it out in a PR. Main thing is to avoid breaking changes if possible.

**Comment by dmnyu** [comment]
Ok, just made the PR. I made a new StartWithAltTMP function rather than messing with the existing functions or the server struct.

**Comment by dmnyu** [comment]
@tbpg I just cancelled the pull request and am going to open a new issue that better describes the problem.
