### ISSUE TITLE
Pass a request or request header to Parse

### ISSUE THREAD

**Issue by nathj07** [google/go-tika#36]
I'm experimenting with this library and it is very good, so thank you. However, the default behaviour from the Tika server seems to be to return extracted text as HTML. According to the Tika docs making the request with the header `"Accept: text/plain"` will return plain text. This would be much better in my use case.

I see in the code that [client.call method](https://github.com/google/go-tika/blob/main/tika/tika.go#L117) allows the caller to pass in a `http.Header`. The issue is that the public methods do not. It would be great if [Parse](https://github.com/google/go-tika/blob/main/tika/tika.go#L158), and [ParseReader](https://github.com/google/go-tika/blob/main/tika/tika.go#L164) could be updated to accept `http.Header` and then this was passed on to `callString` and `call`.

I'm happy to open a PR for this if that would help.

**Comment by nathj07** [comment]
Here's the PR: https://github.com/google/go-tika/pull/37 I opted for the simplest solution of passing the header. That made more sense of the current workflow and where the request is currently made.

**Comment by tbpg** [comment]
Thanks for the PR! I left a comment about the exact API, but I'm open overall. :smile:

**Comment by perelin** [comment]
Brilliant, thanks for this addition! Just one remark: the current tag 0.2.0 doesn't have it yet. I actively needed to install the specific ref, since `go get` still defaults to 0.2.0.

**Comment by tbpg** [comment]
Thanks for the nudge. I just released `v0.3.0`. Marking this as fixed.
